/*
* author: ejaetan
*
* Each new term in the Fibonacci sequence is generated by adding the previous 
* two terms. By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values
* do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

long fibotail(long n, long a, long b);

int main()
{
	long i = 0;
	long a,b,c,d;
	
	while (fibotail(i, 0, 1) < 4000000)
		i++;
	a = --i;

	for (b = 0; b <= a; b++)
	{
		c = fibotail(b, 0 , 1);
		if(c%2 == 0)
			d = d+c;
	}
	printf("%ld\n", d);
	
	return 0;	
		
}

long fibotail(long n, long a, long b)
{
	if (n == 0)
		return a;
	else if (n == 1)
		return b;
	else if (n > 1)
		return fibotail(n-1, b, a+b);	
}